Change it to a more better dark themed color
EzarDev/site pull request #3
Opened 2022-06-17 12:26 UTC by ItsNotAlexy

2022-06-17 12:54 UTC, toolifelesstocode commented
Can you explain what this pull request is for, by editing the pull request description.

2022-06-18 07:29 UTC, ooliver1 requested changes
Wouldn't it make more sense for these to be variables so you only have to change it in one place

2022-06-20 05:46 UTC, toolifelesstocode requested changes
Maybe make the purple not that dark, by using this hex color #5c18ae

2022-06-20 05:46 UTC, toolifelesstocode commented on css/history.css
> +    background: #1B2430;
```suggestion
    background: #5c18ae;
```

2022-06-20 05:46 UTC, toolifelesstocode commented on css/404.css
> +    background-color: #1B2430;
```suggestion
    background-color: #5c18ae;
``` 
Maybe try this purple, the website looks fine from the preview, but just very dark.

2022-06-20 05:46 UTC, toolifelesstocode commented on css/404.css
> +    color: #1B2430;
```suggestion
    color: #5c18ae;
```

2022-06-20 05:46 UTC, toolifelesstocode commented on css/home.css
> +    background: #1B2430;
```suggestion
    background: #5c18ae;
```

2022-06-20 05:46 UTC, toolifelesstocode commented on css/home.css
> +    color: #1B2430;
```suggestion
    color: #5c18ae;
```

2022-06-20 05:46 UTC, toolifelesstocode commented on css/home.css
> +    background-color: #1B2430;
```suggestion
    background-color: #5c18ae;
```

2022-06-27 09:32 UTC, toolifelesstocode commented
@ItsNotAlexy Bump on this.

2022-09-02 09:00 UTC, ItsNotAlexy commented
Closing because of new rewrite.

2022-09-02 09:00 UTC, closed without merging